//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_CustomerProduct
    {
        public int CustomerProductId { get; set; }
        public int CustomerID { get; set; }
        public string ProductCode { get; set; }
        public Nullable<System.DateTime> SubscriptionDate { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<bool> SubscriptionStatus { get; set; }
        public bool DeletedFlag { get; set; }
    }
}
