//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_IssueCode
    {
        public AA_IssueCode()
        {
            this.PX_AgendaItem = new HashSet<PX_AgendaItem>();
        }
    
        public string IssueCode { get; set; }
        public string IssueCategoryCode { get; set; }
        public string IssueShortText { get; set; }
        public bool HasSubItems { get; set; }
        public bool IsVoteAtSubItem { get; set; }
        public bool IsDirectorIssue { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] ConcurrencyTmstp { get; set; }
        public bool DeletedFlag { get; set; }
        public int IssueCodeType { get; set; }
    
        public virtual ICollection<PX_AgendaItem> PX_AgendaItem { get; set; }
    }
}
