//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AA_Security
    {
        public AA_Security()
        {
            this.AA_SecuritySymbol = new HashSet<AA_SecuritySymbol>();
            this.PX_Meeting = new HashSet<PX_Meeting>();
            this.PX_WatchListSecurity = new HashSet<PX_WatchListSecurity>();
        }
    
        public int SecurityID { get; set; }
        public string IssuerName { get; set; }
        public string IssueData { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] ConcurrencyTmstp { get; set; }
        public bool DeletedFlag { get; set; }
        public Nullable<bool> MergedIndicator { get; set; }
        public Nullable<int> MergedWithIssuerID { get; set; }
        public Nullable<bool> GLCoverageUniverseIndicator { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public int FactVersion { get; set; }
        public bool IsInCoverageUniverse { get; set; }
        public Nullable<int> rpOrgID { get; set; }
        public string CountryOfOrigin { get; set; }
        public string OldIssuerName { get; set; }
        public Nullable<bool> IsUpdated { get; set; }
        public Nullable<double> Shares { get; set; }
        public string ComType { get; set; }
        public Nullable<long> OutstandingShares { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> EDI_IssID { get; set; }
        public Nullable<bool> EDIIssuerNameOverride { get; set; }
    
        public virtual ICollection<AA_SecuritySymbol> AA_SecuritySymbol { get; set; }
        public virtual ICollection<PX_Meeting> PX_Meeting { get; set; }
        public virtual ICollection<PX_WatchListSecurity> PX_WatchListSecurity { get; set; }
    }
}
