//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_AccountGroup
    {
        public AM_AccountGroup()
        {
            this.PX_GroupAccount = new HashSet<PX_GroupAccount>();
        }
    
        public int AccountGroupId { get; set; }
        public string GroupTypeCode { get; set; }
        public string GroupName { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> ProfileID { get; set; }
    
        public virtual ICollection<PX_GroupAccount> PX_GroupAccount { get; set; }
    }
}
