//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_AccountHoldings
    {
        public int AccountID { get; set; }
        public int SecuritySymbolID { get; set; }
        public decimal SharesHeld { get; set; }
        public Nullable<decimal> SharesOnLoan { get; set; }
        public System.DateTime HoldingStartDate { get; set; }
        public Nullable<int> BatchControlId { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] ConcurrencyTmstp { get; set; }
    }
}
