//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class AM_SubAccount
    {
        public int SubAccountId { get; set; }
        public int AccountId { get; set; }
        public string SubAccountName { get; set; }
        public string SubAccountStatusCode { get; set; }
    
        public virtual AM_Account AM_Account { get; set; }
    }
}
