//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_Policy
    {
        public PL_Policy()
        {
            this.PX_AgendaSubItemRecommendations = new HashSet<PX_AgendaSubItemRecommendations>();
            this.PX_ProposalRecommendations = new HashSet<PX_ProposalRecommendations>();
            this.PX_WorkflowNotes_AgendaPolicy = new HashSet<PX_WorkflowNotes_AgendaPolicy>();
        }
    
        public int PolicyID { get; set; }
        public string PolicyTag { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public string PolicyName { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string PolicyTypeCode { get; set; }
        public Nullable<int> PolicyOwnerUserId { get; set; }
        public string DefaultDirectiveCode_ { get; set; }
        public string Note { get; set; }
        public bool IsActive { get; set; }
        public bool IsDefault { get; set; }
        public bool IsGlobal { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] ConcurrencyTmstp { get; set; }
        public Nullable<System.DateTime> LastGeneratedTmstp { get; set; }
        public Nullable<System.DateTime> LastCriticalChangeTmstp { get; set; }
        public int MajorVersion { get; set; }
        public bool IsConservative { get; set; }
        public Nullable<bool> IsTNAInstructable { get; set; }
        public Nullable<bool> IsZeroSharesInstructable { get; set; }
        public string SWOPDefaultDirectiveCode { get; set; }
    
        public virtual AA_Customer AA_Customer { get; set; }
        public virtual ICollection<PX_AgendaSubItemRecommendations> PX_AgendaSubItemRecommendations { get; set; }
        public virtual ICollection<PX_ProposalRecommendations> PX_ProposalRecommendations { get; set; }
        public virtual ICollection<PX_WorkflowNotes_AgendaPolicy> PX_WorkflowNotes_AgendaPolicy { get; set; }
    }
}
