//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_PolicyIssueRules
    {
        public int PolicyIssueRuleID { get; set; }
        public Nullable<int> RuleTemplateID { get; set; }
        public Nullable<int> PolicyIssueID { get; set; }
        public string THENRecommendation { get; set; }
        public string ELSERecommendation { get; set; }
        public Nullable<System.DateTime> LastExecutedDate { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string Description { get; set; }
        public string RuleName { get; set; }
        public string RuleStatement { get; set; }
        public string SerializedAST { get; set; }
        public int Version { get; set; }
        public int RuleTemplateSeed { get; set; }
    }
}
