//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PL_PolicyIssue
    {
        public int PolicyIssueID { get; set; }
        public int PolicyID { get; set; }
        public string IssueCode { get; set; }
        public Nullable<bool> IssueComplete { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool PositiveFailSafeFlag { get; set; }
        public bool NegativeFailSafeFlag { get; set; }
        public string FailSafeEmailID { get; set; }
        public string DefaultDirectiveCode { get; set; }
        public bool DeletedFlag { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] ConcurrencyTmstp { get; set; }
        public string Explanation { get; set; }
        public string SWOPDefaultDirectiveCode { get; set; }
    }
}
