//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PX_AgendaSubItem
    {
        public PX_AgendaSubItem()
        {
            this.PX_AgendaSubItemRecommendations = new HashSet<PX_AgendaSubItemRecommendations>();
        }
    
        public int AgendaSubItemID { get; set; }
        public string AgendaSubItemText { get; set; }
        public string AgendaSubItemNumber { get; set; }
        public int AgendaItemID { get; set; }
        public Nullable<int> BatchControlId { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<bool> IsManuallyEntered { get; set; }
        public string AgendaSubItemLongText { get; set; }
        public string NewSubProposalLongText { get; set; }
        public Nullable<bool> SubProposalTextHasChanged { get; set; }
        public Nullable<bool> PromoteNewSubProposalText { get; set; }
        public Nullable<System.DateTime> SubProposalTextChangedDate { get; set; }
    
        public virtual PX_AgendaItem PX_AgendaItem { get; set; }
        public virtual ICollection<PX_AgendaSubItemRecommendations> PX_AgendaSubItemRecommendations { get; set; }
    }
}
