//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PX_AgendaItem
    {
        public PX_AgendaItem()
        {
            this.PX_AgendaSubItem = new HashSet<PX_AgendaSubItem>();
            this.PX_ProposalRecommendations = new HashSet<PX_ProposalRecommendations>();
        }
    
        public int AgendaItemID { get; set; }
        public int AgendaID { get; set; }
        public string IssueCode { get; set; }
        public string ProposalNumber { get; set; }
        public string ProposalLabel { get; set; }
        public string ProposalTypeCode { get; set; }
        public string ProposalVoteOptionCode { get; set; }
        public string ProposalText { get; set; }
        public Nullable<int> NumberOfDirectors { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] ConcurrencyTmstp { get; set; }
        public Nullable<bool> IsManuallyEntered { get; set; }
        public string ProposalLongText { get; set; }
        public string RPProposalID { get; set; }
        public string NewProposalLongText { get; set; }
        public Nullable<bool> ProposalTextHasChanged { get; set; }
        public Nullable<bool> PromoteNewProposalText { get; set; }
        public Nullable<System.DateTime> ProposalTextChangedDate { get; set; }
        public Nullable<bool> IsCumulativeVoting { get; set; }
        public Nullable<int> CumulativeVotingMultiplier { get; set; }
    
        public virtual AA_IssueCode AA_IssueCode { get; set; }
        public virtual PX_Agenda PX_Agenda { get; set; }
        public virtual ICollection<PX_AgendaSubItem> PX_AgendaSubItem { get; set; }
        public virtual ICollection<PX_ProposalRecommendations> PX_ProposalRecommendations { get; set; }
    }
}
