//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PX_Agenda
    {
        public PX_Agenda()
        {
            this.PX_AgendaItem = new HashSet<PX_AgendaItem>();
            this.PX_Ballot = new HashSet<PX_Ballot>();
            this.PX_WorkflowNotes_AgendaPolicy = new HashSet<PX_WorkflowNotes_AgendaPolicy>();
        }
    
        public int AgendaID { get; set; }
        public int MeetingID { get; set; }
        public string AgendaKey { get; set; }
        public Nullable<System.DateTime> FileProcessingDate { get; set; }
        public string CommitteeCode { get; set; }
        public string StatusCode { get; set; }
        public Nullable<int> BatchControlId { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] ConcurrencyTmstp { get; set; }
        public Nullable<bool> IsManuallyEntered { get; set; }
        public int AgendaVersion { get; set; }
        public Nullable<int> RPReportID { get; set; }
        public Nullable<System.DateTime> RPPublishDate { get; set; }
        public int FactVersion { get; set; }
        public double FactServicePercentage { get; set; }
        public string OriginalAgendaKey { get; set; }
        public Nullable<bool> IsCumulativeVoting { get; set; }
    
        public virtual PX_Meeting PX_Meeting { get; set; }
        public virtual ICollection<PX_AgendaItem> PX_AgendaItem { get; set; }
        public virtual ICollection<PX_Ballot> PX_Ballot { get; set; }
        public virtual ICollection<PX_WorkflowNotes_AgendaPolicy> PX_WorkflowNotes_AgendaPolicy { get; set; }
    }
}
