//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PX_BallotAuditTrail
    {
        public int BallotAuditTrailID { get; set; }
        public int BallotID { get; set; }
        public string ControlNumberKey { get; set; }
        public string BallotStatusCode { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string VoteStatusCode { get; set; }
        public Nullable<bool> IsCopiedForReporting { get; set; }
        public Nullable<decimal> NoOfShares { get; set; }
        public Nullable<decimal> BallotSharesOnLoan { get; set; }
        public string ProposalVotes { get; set; }
        public string DirectorVotes { get; set; }
        public Nullable<System.DateTime> InstructedDate { get; set; }
        public Nullable<int> LogicalBallotID { get; set; }
        public Nullable<bool> NonStandardVote { get; set; }
        public Nullable<int> InstructedBy { get; set; }
    
        public virtual PX_Ballot PX_Ballot { get; set; }
    }
}
