//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PX_BallotVotes
    {
        public PX_BallotVotes()
        {
            this.PX_BallotSubItemVotes = new HashSet<PX_BallotSubItemVotes>();
        }
    
        public int BallotVoteID { get; set; }
        public int BallotID { get; set; }
        public int AgendaItemID { get; set; }
        public string ActualVoteCode { get; set; }
        public string VotingInstructions { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] ConcurrencyTmstp { get; set; }
        public Nullable<bool> VoteAgainstPolicy { get; set; }
    
        public virtual PX_Ballot PX_Ballot { get; set; }
        public virtual ICollection<PX_BallotSubItemVotes> PX_BallotSubItemVotes { get; set; }
    }
}
