//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PX_Ballot
    {
        public PX_Ballot()
        {
            this.PX_BallotAuditTrail = new HashSet<PX_BallotAuditTrail>();
            this.PX_BallotVotes = new HashSet<PX_BallotVotes>();
            this.PX_Shares = new HashSet<PX_Shares>();
        }
    
        public int BallotID { get; set; }
        public string BallotVoteIndicatorCode { get; set; }
        public Nullable<System.DateTime> VoteDate { get; set; }
        public string ControlNumberKey { get; set; }
        public string BallotStatusCode { get; set; }
        public int AccountID { get; set; }
        public Nullable<decimal> NoOfShares { get; set; }
        public string ClassOfStockCode { get; set; }
        public int AgendaID { get; set; }
        public string InstitutionID { get; set; }
        public System.DateTime FileProcessingDate { get; set; }
        public string AppointeeName { get; set; }
        public string StatusCode { get; set; }
        public string Comments { get; set; }
        public string ProviderSecurityId { get; set; }
        public string ProviderIssuerCd { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] ConcurrencyTmstp { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> ValidatedDate { get; set; }
        public bool IsManuallyEntered { get; set; }
        public Nullable<int> BatchControlID { get; set; }
        public int SecuritySymbolID { get; set; }
        public string ProviderCustodianAccountNumber { get; set; }
        public string Provider { get; set; }
        public string DeliveredModeCode { get; set; }
        public string BatchMarker { get; set; }
        public string DeliveryNote { get; set; }
        public bool IsUngroupedBallot { get; set; }
        public string VoteStatusCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string SettlementLocation { get; set; }
        public Nullable<int> CustodianSubAccountId { get; set; }
        public string EntryComments { get; set; }
        public Nullable<bool> IsAutoGenerated { get; set; }
        public Nullable<bool> IsAutoInstructed { get; set; }
        public Nullable<int> Createdby { get; set; }
        public Nullable<bool> IsCopiedForReporting { get; set; }
        public Nullable<System.DateTime> cutoffdate { get; set; }
        public Nullable<decimal> BallotSharesOnLoan { get; set; }
        public Nullable<System.DateTime> SubCustodianCutOffDate { get; set; }
        public bool HasMeetingChangedToContested { get; set; }
        public Nullable<int> LatestBallotID { get; set; }
        public Nullable<int> LastApprovedBy { get; set; }
        public string RecommendationFlavorCode { get; set; }
        public Nullable<System.DateTime> InstructedDate { get; set; }
        public Nullable<int> LogicalBallotID { get; set; }
        public Nullable<bool> NonStandardVote { get; set; }
        public Nullable<decimal> AbsoluteAmount { get; set; }
        public Nullable<decimal> VotedAmount { get; set; }
        public Nullable<decimal> PartialVotePercentage { get; set; }
        public bool IsPartialVote { get; set; }
        public bool IsSplitVote { get; set; }
        public string BlockingIndicator { get; set; }
        public Nullable<int> InstructedBy { get; set; }
        public bool IsZeroSharesChange { get; set; }
    
        public virtual AM_Account AM_Account { get; set; }
        public virtual PX_Agenda PX_Agenda { get; set; }
        public virtual PX_LogicalBallot PX_LogicalBallot { get; set; }
        public virtual PX_WorkflowNotes_Ballot PX_WorkflowNotes_Ballot { get; set; }
        public virtual ICollection<PX_BallotAuditTrail> PX_BallotAuditTrail { get; set; }
        public virtual ICollection<PX_BallotVotes> PX_BallotVotes { get; set; }
        public virtual ICollection<PX_Shares> PX_Shares { get; set; }
    }
}
