//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PX_Group
    {
        public int GroupID { get; set; }
        public Nullable<System.DateTime> DateLastModified { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<bool> UngroupedByBlocking { get; set; }
    }
}
