//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PX_IssuerNotes
    {
        public int NoteID { get; set; }
        public int IssuerID { get; set; }
        public int CustomerID { get; set; }
        public string NoteText { get; set; }
        public System.DateTime Date { get; set; }
        public string Subject { get; set; }
        public string ContactName { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
    }
}
