//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PX_Meeting
    {
        public PX_Meeting()
        {
            this.PX_Agenda = new HashSet<PX_Agenda>();
        }
    
        public int MeetingID { get; set; }
        public string JobNumber { get; set; }
        public int SecurityID { get; set; }
        public string ProviderSecurityID { get; set; }
        public string ProviderIssueTypeCd { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string MeetingTypeCode { get; set; }
        public Nullable<bool> IsContested { get; set; }
        public Nullable<System.DateTime> HoldReconciliationDate { get; set; }
        public Nullable<bool> IsAllowSplitVote { get; set; }
        public Nullable<bool> IsAllowPartialVote { get; set; }
        public Nullable<bool> IsBlockingMarket { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public string MeetingCityCode { get; set; }
        public Nullable<System.DateTime> VoteDeadlineDate { get; set; }
        public string MeetingStatusCode { get; set; }
        public string MeetingStatusReasonCode { get; set; }
        public string MeetingClassificationLevelCode { get; set; }
        public Nullable<bool> IsRecordDateMarket { get; set; }
        public string CommonCode { get; set; }
        public string QuickCode { get; set; }
        public string ParValue { get; set; }
        public Nullable<System.DateTime> FileProcessingDate { get; set; }
        public Nullable<int> DataProviderId { get; set; }
        public Nullable<int> BatchControlId { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] ConcurrencyTmstp { get; set; }
        public Nullable<bool> IsManuallyEntered { get; set; }
        public Nullable<int> ProviderSecuritySymbolID { get; set; }
        public Nullable<bool> ISCopy { get; set; }
        public Nullable<int> MeetingGroupId { get; set; }
        public string MeetingReconciliationTypeCode { get; set; }
        public Nullable<bool> IsCopiedForReporting { get; set; }
        public string OriginalJobNumber { get; set; }
        public Nullable<System.DateTime> SharesDependentChangeDate { get; set; }
    
        public virtual AA_Security AA_Security { get; set; }
        public virtual ICollection<PX_Agenda> PX_Agenda { get; set; }
    }
}
