//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PX_MissingBallotNote
    {
        public int MissingBallotNoteID { get; set; }
        public int MissingBallotID { get; set; }
        public Nullable<int> NoteId { get; set; }
    }
}
