//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PX_MissingBallot
    {
        public int MissingBallotID { get; set; }
        public int AccountID { get; set; }
        public string AccountReconciliationStatusCode { get; set; }
        public string OtherReconciliationStatusReason { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] ConcurrencyTmstp { get; set; }
        public int SecuritySymbolID { get; set; }
        public Nullable<int> MeetingID { get; set; }
        public Nullable<System.DateTime> ReconciliationDate { get; set; }
        public string ReconciliationStatusCode { get; set; }
    }
}
