//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PX_ProposalRecommendations
    {
        public int ProposalRecommendationID { get; set; }
        public Nullable<int> PolicyID { get; set; }
        public int AgendaItemID { get; set; }
        public string RecommendedVoteCode { get; set; }
        public string RecommendedByCode { get; set; }
        public string RecommendationText { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<bool> IsRecoChanged { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public bool MgmtRecHasChanged { get; set; }
        public string NewMgmtRecVoteCode { get; set; }
        public bool PromoteNewMgmtRecVoteCode { get; set; }
        public Nullable<System.DateTime> NewMgmtRecChangedDate { get; set; }
    
        public virtual PL_Policy PL_Policy { get; set; }
        public virtual PX_AgendaItem PX_AgendaItem { get; set; }
    }
}
