//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PX_VoteExecutionProfile
    {
        public PX_VoteExecutionProfile()
        {
            this.PX_VoteExecutionNonVotingMarkets = new HashSet<PX_VoteExecutionNonVotingMarkets>();
            this.PX_VoteExecutionVotingMarketException = new HashSet<PX_VoteExecutionVotingMarketException>();
        }
    
        public int VoteExecutionProfileID { get; set; }
        public string VoteExecutionProfileName { get; set; }
        public string DefaultDirectiveCode { get; set; }
        public string AutoInstructOptionCode { get; set; }
        public Nullable<bool> IsShareBlockingTNAHold { get; set; }
        public bool IsHoldingsLiquidatedTNA { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public byte[] ConcurrencyTmstp { get; set; }
        public Nullable<bool> IsShareBlockingTNAWithoutSending { get; set; }
        public Nullable<int> POATNAOption { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public Nullable<int> ApplyInstructionCode { get; set; }
    
        public virtual AA_Customer AA_Customer { get; set; }
        public virtual ICollection<PX_VoteExecutionNonVotingMarkets> PX_VoteExecutionNonVotingMarkets { get; set; }
        public virtual ICollection<PX_VoteExecutionVotingMarketException> PX_VoteExecutionVotingMarketException { get; set; }
    }
}
