//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OflineViewer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PX_WatchList
    {
        public PX_WatchList()
        {
            this.PX_WatchListAccounts = new HashSet<PX_WatchListAccounts>();
            this.PX_WatchListSecurity = new HashSet<PX_WatchListSecurity>();
            this.PX_WatchListUser = new HashSet<PX_WatchListUser>();
        }
    
        public int WatchListID { get; set; }
        public int CustomerID { get; set; }
        public string WatchListName { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] ConcurrencyTmstp { get; set; }
        public int ForAllAccounts { get; set; }
    
        public virtual ICollection<PX_WatchListAccounts> PX_WatchListAccounts { get; set; }
        public virtual ICollection<PX_WatchListSecurity> PX_WatchListSecurity { get; set; }
        public virtual ICollection<PX_WatchListUser> PX_WatchListUser { get; set; }
    }
}
